---
abstract: 'form handler written in Moose'
author:
  - 'Gerda Shank'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Differences: 0
  Test::Exception: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-FormHandler
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Class::Load: 0.05
  DateTime: 0
  File::Spec: 0
  HTML::Entities: 0
  Locale::Maketext: 1.09
  Moose: 0.90
  MooseX::Getopt: 0.16
  MooseX::Traits: 0
  MooseX::Types: 0.20
  MooseX::Types::Common: 0
  aliased: 0
  namespace::autoclean: 0.09
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/gshank/html-formhandler/tree/master
version: 0.28001
