---
abstract: 'form handler written in Moose '
author:
  - 'gshank: Gerda Shank <gshank@cpan.org>'
build_requires:
  DateTime::Format::MySQL: 0
  Test::More: 0.77
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-FormHandler
no_index:
  directory:
    - inc
    - t
recommends:
  Catalyst: 0
  Catalyst::Component::InstancePerContext: 0
  Template: 0
  Test::WWW::Mechanize::Catalyst: 0.50
requires:
  Carp: 0
  DBIx::Class: 0
  DateTime: 0
  HTML::Entities: 0
  Locale::Maketext: 1.09
  Moose: 0.59
  MooseX::AttributeHelpers: 0.14
  MooseX::Getopt: 0.16
  UNIVERSAL::require: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.20
