---
abstract: 'form handler written in Moose '
author:
  - 'Gerda Shank, gshank@cpan.org'
build_requires:
  Test::More: 0.77
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-FormHandler
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  DBIx::Class: 0
  Locale::Maketext: 1.09
  Module::Find: 0.05
  Moose: 0.59
  MooseX::AttributeHelpers: 0.14
  Scalar::Util: 1.19
  UNIVERSAL::require: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
